### ISSUE TITLE
A request - not a bug

### ISSUE THREAD

**Issue by Montclair** [LenShustek/Eudora_fix_mbx#3]
IDK if it's possible for you to locate the code that truncates the subject line in the list of e-mail (typically above the preview pane) and change that number to at least 99 (preferably 255).  Eudora truncates the appearance of the subject line at 62 or 63 characters.  Sorry if I should have posted this via some other method on Github.

**Comment by LenShustek** [comment]
My apology for the delayed response; the email notification of this issue scrolled off the top of my Eudora inbox and I neglected to look back until now.

Unfortunately the 64-character limit on the length of the subject line in the message list can't be changed. It's built into the structure of the TOC (table of contents) file, which has a fixed 64-byte field to store the subject.

The good news is that the subject stored in the message itself doesn't have that limitation, so you can see the whole thing when you view the message.

**Comment by Montclair** [comment]
No problem.  Thanks for replying and for the technical explanation!

    On Thursday, January 12, 2023 at 12:28:02 PM EST, Len Shustek ***@***.***> wrote:  
 
 


My apology for the delayed response; the email notification of this issue scrolled off the top of my Eudora inbox and I neglected to look back until now.

Unfortunately the 64-character limit on the length of the subject line in the message list can't be changed. It's built into the structure of the TOC (table of contents) file, which has a fixed 64-byte field to store the subject.

The good news is that the subject stored in the message itself doesn't have that limitation, so you can see the whole thing when you view the message.
